VARONE
    DIM 10
.VARTWO INIT "SECOND VAR"
.VARTHREE FORM 2
.VARFOUR FORM "-10"

AList list
VARONE DIM 10
VARTWO init "second var"
VARTHREE form 2
VARFOUR form "-10"
VARFIVE dim 10
    listend


    MOVE "HELLO" TO VARONE
    MOVE "20" TO VARTHREE

TOP
    DISPLAY *ES,VARONE
. SIMPLE COMMENT LINE
    DISPLAY *P=10:2,VARTWO
* FORM FEED COMMENT LINE
    DISPLAY VARTHREE
+ FORCED FORM FEED COMMENT LINE
    DISPLAY *P=10:4,VARFOUR!

    ADD "1" TO VARTHREE
    GOTO TOP IF (VARTHREE <= 25)
    STOP
